version: '1'
services:
  app:
    container_name: 10-CALENDAR-BACKEND
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "4000:4000"